name: 'Create Asana Task'
author: 'Honeycomb'
description: 'Trigger task creation in Asana from Github'

inputs:
  asana-secret: 
    required: true
    description: 'Asana PAT'
  asana-workspace-id:
    required: true
    description: 'Your Asana Workspace ID'
  asana-project-id:
    required: true
    description: 'Your Asana Project ID'
  asana-section-id:
    required: true
    description: 'Your Asana Section ID (column the task should belong to)'
  asana-task-name:
    required: true
    description: 'Name for Asana task that will be created'
  asana-task-description:
    description: 'Description for Asana task that will be created'

runs:
  using: 'node16'
  main: 'dist/index.js'
